services:
  - type: web
    name: dns-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /assets/*.css
        name: Content-Type
        value: text/css
      - path: /assets/*.js
        name: Content-Type
        value: application/javascript
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*
        name: Cache-Control
        value: no-cache 